version: '3.8'

services:
  app:
    build: .
    restart: always
    depends_on:
      - db
      - redis
      - ollama
    ports:
      - "3000:3000"
    env_file: 
      - .env
    volumes:
      - app-storage:/rails/storage
    command: ["bin/rails", "server", "-b", "0.0.0.0"]

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME_PROD
    volumes:
      - db-storage:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama:latest
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama-storage:/root/.ollama

volumes:
  db-storage:
  app-storage:
  ollama-storage:
