development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: chat_spinoff_development

test:
  adapter: test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: chat_spinoff_production
