default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_test

production:
  primary:
    <<: *default
    database: <%= ENV['DB_NAME_PROD'] %>

  cache:
    <<: *default
    database: <%= ENV['DB_NAME_PROD'] %>_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: <%= ENV['DB_NAME_PROD'] %>_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: <%= ENV['DB_NAME_PROD'] %>_cable
    migrations_paths: db/cable_migrate
